"""Expected edge patterns for the ConfigManBearPig integration test runner."""

EXPECTED_EDGES_TEMPLATE = [{'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The CAS primary site server has local administrator rights on the CAS site database server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'cas-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'cas-db.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The CAS primary site server has local administrator rights on the service connection point server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'cas-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'cas-scp.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 primary site server has local administrator rights on the site database server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-db.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 primary site server has local administrator rights on the SMS Provider server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-sms.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 primary site server has local administrator rights on the management point server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-mp.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 primary site server has local administrator rights on the distribution point server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-dp.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 primary site server has local administrator rights on the passive site server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-psv.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Count': 1,
  'Description': 'The PS1 passive site server has local administrator rights on the primary site server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-psv.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}}},
 {'Kind': 'LocalAdminRequired',
  'Negative': True,
  'Description': 'The PS2 primary site server does not have local administrator rights on the PS1 site database server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps2-pss.$Domain'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-db.$Domain'}}},
 {'Kind': 'CoerceAndRelayToAdminService',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce the PS1 primary site server and relay authentication to the '
                 'AdminService on the PS1 SMS Provider, coerce the PS1 primary site server and relay authentication to '
                 'the AdminService on the PS1 passive site server, coerce the PS1 passive site server and relay '
                 'authentication to the AdminService on the PS1 primary site server, and coerce the PS1 passive site '
                 'server and relay authentication to the AdminService on the PS1 SMS Provider',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'PS1'}},
  'Properties': {'coercionVictimAndRelayTargetPairs': ['Coerce ps1-psv.mayyhem.com, relay to ps1-pss.mayyhem.com',
                                                       'Coerce ps1-pss.mayyhem.com, relay to ps1-psv.mayyhem.com',
                                                       'Coerce ps1-pss.mayyhem.com, relay to ps1-sms.mayyhem.com',
                                                       'Coerce ps1-psv.mayyhem.com, relay to ps1-sms.mayyhem.com']}},
 {'Kind': 'CoerceAndRelayToMSSQL',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the MSSQL service on the CAS site '
                 'database server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': 'MAYYHEM\\CAS-PSS$@*:1433'}},
  'Properties': {'coercionVictimAndRelayTargetPairs': ['Coerce cas-pss.mayyhem.com, relay to '
                                                       'cas-db.mayyhem.com:1433']}},
 {'Kind': 'CoerceAndRelayToMSSQL',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the MSSQL service on the PS1 site '
                 'database server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': 'MAYYHEM\\PS1-PSS$@*:1433'}},
  'Properties': {'coercionVictimAndRelayTargetPairs': ['Coerce ps1-pss.mayyhem.com, relay to '
                                                       'ps1-db.mayyhem.com:1433']}},
 {'Kind': 'CoerceAndRelayToMSSQL',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the MSSQL service on the PS1 site '
                 'database server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': 'MAYYHEM\\PS1-SMS$@*:1433'}},
  'Properties': {'coercionVictimAndRelayTargetPairs': ['Coerce ps1-sms.mayyhem.com, relay to '
                                                       'ps1-db.mayyhem.com:1433']}},
 {'Kind': 'CoerceAndRelayToMSSQL',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the MSSQL service on the PS1 site '
                 'database server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': 'MAYYHEM\\PS1-PSV$@*:1433'}},
  'Properties': {'coercionVictimAndRelayTargetPairs': ['Coerce ps1-psv.mayyhem.com, relay to '
                                                       'ps1-db.mayyhem.com:1433']}},
 {'Kind': 'CoerceAndRelayToSMB',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the SMB service on the PS1 SMS '
                 'Provider',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-sms.$Domain'}}},
 {'Kind': 'CoerceAndRelayToSMB',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the SMB service on the PS1 site '
                 'database server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-db.$Domain'}}},
 {'Kind': 'CoerceAndRelayToSMB',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the SMB service on the PS1 primary '
                 'site server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-pss.$Domain'}}},
 {'Kind': 'CoerceAndRelayToSMB',
  'Count': 1,
  'Description': 'Authenticated Users group can coerce and relay authentication to the SMB service on the PS1 passive '
                 'site server',
  'Source': {'Kinds': ['Group', 'Base'], 'Properties': {'id': '*-S-1-5-11'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-psv.$Domain'}}},
 {'Kind': 'HasSession',
  'Count': 1,
  'Description': 'The MSSQL service account has an active session on the CAS site database server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'cas-db.$Domain'}},
  'Target': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'sqlsccmsvc', 'id': 'S-1-5-21-*'}}},
 {'Kind': 'HasSession',
  'Count': 1,
  'Description': 'The MSSQL service account has an active session on the PS1 site database server',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-db.$Domain'}},
  'Target': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'sqlsccmsvc', 'id': 'S-1-5-21-*'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The CAS site database MSSQL server contains the CM_<SiteCode> database',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}},
  'Target': {'Kinds': ['MSSQL_Database'], 'Properties': {'name': 'CM_CAS'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The CAS site database MSSQL server contains the CAS-PSS$ login',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433', 'name': 'CAS-DB*'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*cas-pss$@*:1433'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The CAS site database contains the db_owner database role',
  'Source': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_CAS'}},
  'Target': {'Kinds': ['MSSQL_DatabaseRole'], 'Properties': {'id': 'db_owner@*:1433\\CM_CAS'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The CAS site database contains the CAS-PSS$ user',
  'Source': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_CAS'}},
  'Target': {'Kinds': ['MSSQL_DatabaseUser'], 'Properties': {'id': '*cas-pss$@*:1433\\CM_CAS'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The PS1 site database MSSQL server contains the CM_<SiteCode> database',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}},
  'Target': {'Kinds': ['MSSQL_Database'], 'Properties': {'name': 'CM_PS1'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The PS1 site database MSSQL server contains the PS1-PSS$ login',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*ps1-pss$@*:1433'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The PS1 site database contains the db_owner database role',
  'Source': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_PS1'}},
  'Target': {'Kinds': ['MSSQL_DatabaseRole'], 'Properties': {'id': 'db_owner@*:1433\\CM_PS1'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 1,
  'Description': 'The PS1 site database contains the PS1-PSS$ user',
  'Source': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_PS1'}},
  'Target': {'Kinds': ['MSSQL_DatabaseUser'], 'Properties': {'id': '*ps1-pss$@*:1433\\CM_PS1'}}},
 {'Kind': 'MSSQL_Contains',
  'Count': 3,
  'Description': 'The MSSQL servers (cas-db, ps1-db, and ps1-psv) contain the sysadmin server role',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}},
  'Target': {'Kinds': ['MSSQL_ServerRole'], 'Properties': {'id': 'sysadmin@*:1433'}}},
 {'Kind': 'MSSQL_ControlDB',
  'Count': 2,
  'Description': 'The db_owner MSSQL database role controls the site database on cas-db and ps1-db',
  'Source': {'Kinds': ['MSSQL_DatabaseRole'], 'Properties': {'id': 'db_owner@*:1433\\CM_*'}},
  'Target': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_*'}}},
 {'Kind': 'MSSQL_ControlServer',
  'Count': 3,
  'Description': 'The sysadmin MSSQL server role controls the server instance on cas-db, ps1-db, and ps1-psv',
  'Source': {'Kinds': ['MSSQL_ServerRole'], 'Properties': {'id': 'sysadmin@*:1433'}},
  'Target': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}}},
 {'Kind': 'MSSQL_ExecuteOnHost',
  'Count': 3,
  'Description': 'The MSSQL servers (cas-db, ps1-db, and ps1-psv) can execute commands on their hosts',
  'Source': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}},
  'Target': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*'}}},
 {'Kind': 'MSSQL_GetAdminTGS',
  'Count': 2,
  'Description': 'The site database MSSQL service account can request a TGS for any domain login on the server '
                 'instance',
  'Source': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'sqlsccmsvc', 'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}}},
 {'Kind': 'MSSQL_GetTGS',
  'Count': 4,
  'Description': 'The site database MSSQL service account can request a TGS for any domain login on the server '
                 'instance (CAS-PSS, PS1-PSS, PS1-PSV, and PS1-SMS)',
  'Source': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'sqlsccmsvc', 'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*$:1433'}}},
 {'Kind': 'MSSQL_HasLogin',
  'Count': 4,
  'Description': 'The primary and passive site server and SMS Provider computers have logins on the MSSQL server '
                 'instances (CAS-PSS -> CAS-DB, PS1-PSS -> PS1-DB, PS1-SMS -> PS1-DB, PS1-PSV -> PS1-DB)',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*$:1433'}}},
 {'Kind': 'MSSQL_HostFor',
  'Count': 3,
  'Description': 'The MSSQL server computers (cas-db, ps1-db, and ps1-psv) host the MSSQL server instances',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}}},
 {'Kind': 'MSSQL_IsMappedTo',
  'Count': 4,
  'Description': 'The primary and passive site server and SMS Provider MSSQL server logins (CAS-PSS, PS1-PSS, PS1-PSV, '
                 'and PS1-SMS) are mapped to database users in the site databases',
  'Source': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*$:1433'}},
  'Target': {'Kinds': ['MSSQL_DatabaseUser'], 'Properties': {'id': '*$@*:1433\\CM_*'}}},
 {'Kind': 'MSSQL_MemberOf',
  'Count': 4,
  'Description': 'The primary and passive site server and SMS Provider MSSQL database users (CAS-PSS, PS1-PSS, '
                 'PS1-PSV, and PS1-SMS) are members of the db_owner database role in the site databases',
  'Source': {'Kinds': ['MSSQL_DatabaseUser'], 'Properties': {'id': '*$@*:1433\\CM_*'}},
  'Target': {'Kinds': ['MSSQL_DatabaseRole'], 'Properties': {'id': 'db_owner@*:1433\\CM_*'}}},
 {'Kind': 'MSSQL_MemberOf',
  'Count': 4,
  'Description': 'The primary and passive site server and SMS Provider MSSQL server logins (CAS-PSS, PS1-PSS, PS1-PSV, '
                 'and PS1-SMS) are members of the sysadmin server role on the MSSQL server instances',
  'Source': {'Kinds': ['MSSQL_Login'], 'Properties': {'id': '*$:1433'}},
  'Target': {'Kinds': ['MSSQL_ServerRole'], 'Properties': {'id': 'sysadmin@*:1433'}}},
 {'Kind': 'MSSQL_ServiceAccountFor',
  'Count': 2,
  'Description': 'The site database MSSQL service account is the service account for the MSSQL server instances (CAS '
                 'and PS1 primary and passive)',
  'Source': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'sqlsccmsvc', 'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['MSSQL_Server'], 'Properties': {'id': '*:1433'}}},
 {'Kind': 'SameHostAs',
  'Count': 1,
  'Description': 'The PS1 client device is the same host as the domain joined computer (bi-directional)',
  'Source': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*'}},
  'Target': {'Kinds': ['Computer'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-dev.$Domain'}}},
 {'Kind': 'SameHostAs',
  'Count': 1,
  'Description': 'The PS1 client device is the same host as the domain joined computer (bi-directional)',
  'Source': {'Kinds': ['Computer'], 'Properties': {'id': 'S-1-5-21-*', 'dNSHostName': 'ps1-dev.$Domain'}},
  'Target': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*'}}},
 {'Kind': 'SCCM_AdminsReplicatedTo',
  'Count': 1,
  'Description': 'The PS1 primary site has the same admins as the CAS primary site',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'PS1'}},
  'Target': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'CAS'}}},
 {'Kind': 'SCCM_AdminsReplicatedTo',
  'Count': 1,
  'Description': 'The PS1 primary site has the same admins as the CAS primary site (both directions)',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'CAS'}},
  'Target': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'PS1'}}},
 {'Kind': 'SCCM_AdminsReplicatedTo',
  'Negative': True,
  'Description': 'Admin users in secondary sites are NOT replicated to primary sites (no replication from SEC to PS1 '
                 'or CAS)',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'SEC'}},
  'Target': {'Kinds': ['SCCM_Site'], 'Properties': {'id': '*'}}},
 {'Kind': 'SCCM_AllPermissions',
  'Count': 2,
  'Description': 'The Full Administrator with all collections has all permissions to all primary sites in the '
                 'hierarchy',
  'Source': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'mayyhem\\domainadmin@*'}},
  'Target': {'Kinds': ['SCCM_Site']}},
 {'Kind': 'SCCM_AssignAllPermissions',
  'Count': 8,
  'Description': 'Domain computers hosting the SMS Provider role (CAS-PSS, PS1-PSS, PS1-PSV, PS1-SMS) can assign all '
                 'permissions to any primary site in the hierarchy (CAS, PS1)',
  'Source': {'Kinds': ['Computer', 'Base'], 'Properties': {'id': 'S-1-5-21-*'}},
  'Target': {'Kinds': ['SCCM_Site']}},
 {'Kind': 'SCCM_AssignAllPermissions',
  'Count': 2,
  'Description': 'SCCM primary site databases (CAS-DB\\CM_CAS and PS1-DB\\CM_PS1) can assign all permissions to their '
                 'primary site in the hierarchy (CAS, PS1)',
  'Source': {'Kinds': ['MSSQL_Database'], 'Properties': {'id': '*:1433\\CM_*'}},
  'Target': {'Kinds': ['SCCM_Site']}},
 {'Kind': 'SCCM_AssignSpecificPermissions'},
 {'Kind': 'SCCM_Contains',
  'Count': 2,
  'Description': 'The CAS and PS1 primary sites contain an SCCM admin user',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': '*'}},
  'Target': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'mayyhem\\domainadmin@*'}}},
 {'Kind': 'SCCM_Contains',
  'Count': 2,
  'Description': 'The CAS and PS1 primary sites contain the Full Administrator security role',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': '*'}},
  'Target': {'Kinds': ['SCCM_SecurityRole'], 'Properties': {'id': 'SMS0001R@*'}}},
 {'Kind': 'SCCM_Contains',
  'Count': 2,
  'Description': 'The CAS and PS1 primary sites contain the SMS00001 collection',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': '*'}},
  'Target': {'Kinds': ['SCCM_Collection'], 'Properties': {'id': 'SMS00001@*'}}},
 {'Kind': 'SCCM_FullAdministrator',
  'Count': 14,
  'Description': 'The domainadmin SCCM admin user has the Full Administrator security role over all client devices in '
                 'the hierarchy',
  'Source': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'mayyhem\\domainadmin@*'}},
  'Target': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*'}}},
 {'Kind': 'SCCM_HasADLastLogonUser',
  'Count': 1,
  'Description': 'The PS1 client device has domainuser as the last logged on user in Active Directory',
  'Source': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'name': 'PS1-DEV@PS1'}},
  'Target': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'domainuser', 'id': 'S-1-5-21-*'}}},
 {'Kind': 'SCCM_HasClient',
  'Count': 1,
  'Description': 'PS1-DEV is a client of the PS1 site',
  'Source': {'Kinds': ['SCCM_Site'], 'Properties': {'id': 'PS1'}},
  'Target': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*', 'name': 'PS1-DEV@PS1'}}},
 {'Kind': 'SCCM_HasCurrentUser',
  'Count': 1,
  'Description': 'The PS1 client device has domainuser as the current logged on user (requires manual addition of user '
                 'device affinity after Ludus lab build)',
  'Source': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*', 'name': 'PS1-DEV@PS1'}},
  'Target': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'domainuser', 'id': 'S-1-5-21-*'}}},
 {'Kind': 'SCCM_HasMember',
  'Count': 1,
  'Description': 'The SMS00001 collection contains the PS1 client device',
  'Source': {'Kinds': ['SCCM_Collection'], 'Properties': {'id': 'SMS00001@*'}},
  'Target': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*', 'name': 'PS1-DEV@PS1'}}},
 {'Kind': 'SCCM_HasPrimaryUser',
  'Count': 1,
  'Description': 'The PS1 client device has domainuser as the primary user',
  'Source': {'Kinds': ['SCCM_ClientDevice'], 'Properties': {'id': 'GUID:*', 'name': 'PS1-DEV@PS1'}},
  'Target': {'Kinds': ['User', 'Base'], 'Properties': {'samAccountName': 'domainuser', 'id': 'S-1-5-21-*'}}},
 {'Kind': 'SCCM_IsAssigned',
  'Count': 2,
  'Description': 'The domainadmin SCCM admin user is assigned the Full Administrator security role in the CAS root '
                 'site (plus one dupe that BloodHound dedupes)',
  'Source': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'mayyhem\\domainadmin@*'}},
  'Target': {'Kinds': ['SCCM_SecurityRole'], 'Properties': {'id': 'SMS0001R@*'}}},
 {'Kind': 'SCCM_IsMappedTo',
  'Count': 2,
  'Description': 'The domainadmin user is mapped to an SCCM admin user in the CAS primary site (plus one dupe that '
                 'BloodHound dedupes)',
  'Source': {'Kinds': ['User', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'samAccountName': 'domainadmin'}},
  'Target': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'mayyhem\\domainadmin@*'}}},
 {'Kind': 'SCCM_IsMappedTo',
  'Negative': True,
  'Description': 'The domainuser user is NOT mapped to an SCCM admin user in any primary site',
  'Source': {'Kinds': ['User', 'Base'], 'Properties': {'id': 'S-1-5-21-*', 'samAccountName': 'domainuser'}},
  'Target': {'Kinds': ['SCCM_AdminUser'], 'Properties': {'id': 'domainuser@*'}}}]
